[Interface]
PrivateKey = +WYfbPixVjgVyUrK91zLdx9GSSwRtO4Sot8H+Gxsi0U=
Address = 10.8.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = q5laJW2HlgCSaiFgaVW/4QBxgnrjHFGZajODYf56jXI=
Endpoint = 3.235.16.125:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25

