[Interface]
# The internal private IP subnet for your secure tunnel
Address = 10.8.0.1/24
ListenPort = 51820

# Paste your copied server_private.key string directly below
PrivateKey = J6yVSuz8dcHjQqrRbFd3uzaBKQ+Q+4YL6R5oYzDupwI=

# Linux routing rules: forwards encrypted traffic through the virtual network card
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j ACCEPT